export const ONGOING = 'ONGOING';
export const CANCELLED_BY_PASSANGER = 'CANCELLED_BY_PASSANGER';
export const CONFIRM_RECEIVE = 'CONFIRM_RECEIVE';
export const CONFIRM_ARRIVAL = 'CONFIRM_ARRIVAL';
export const ORDER_ISSUE = 'ORDER_ISSUE';
export const ORDER_FULFILLED = 'ORDER_FULFILLED';
export const ORDER_ISSUE_OVER = 'ORDER_ISSUE_OVER';

